---
- name:  Replicacion PostgreSQL
  hosts: yvao0ju0
  tasks: 
  - name: Comprobación carpeta
    file: path=/tmp/ state=directory
#  - name: Copiar .gitlab-vi.yml 
#    copy: src="./.gitlab-ci.yml" dest=/tmp/.gitlab-ci.yml
  - name: Copiar Docker compose.yml 
    copy: src="docker-compose.yml" dest="/tmp/docker-compose.yml" 
  - name: Copiar docker-entrypoint.sh
    copy: src="docker-entrypoint.sh" dest="/tmp/docker-entrypoint.sh" mode=777
  - name: Copiar Dockerfile 
    copy: src="Dockerfile" dest="/tmp/Dockerfile" mode=777
  - name: Copiar setup-replication.sh 
    copy: src="setup-replication.sh" dest="/tmp/setup-replication.sh" mode=777