---
- hosts: yvao10a0
  tasks: 
  - name: Comprobacion de existencia de carpeta
    file: path="/tmp/Slave" state=directory 
  - name: Copiar DockerFile Slave
    copy: src="./Dockerfile" dest=/tmp/Slave/Dockerfile
  - name: Copiar docker-entrypoint.sh
    copy: src="./docker-entrypoint.sh" dest=/tmp/Slave/docker-entrypoint.sh mode=777
  - name: Copy Gosu Script
    copy: src="./gosu-amd64" dest=/tmp/Slave/gosu mode=777